controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

ajaxEtat:
    path: /tache/modif
    controller: App\Controller\TacheController::modif
    methods: POST

drag&drop:
    path: /projet/prio
    controller: App\Controller\ProjetController::modif
    methods: POST

modal:
    path: /modal
    controller: App\Controller\TacheController::finish
    methods: POST
