controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

route_ajax:
    path: /tache/modif
    controller: App\Controller\TacheController::modif
    methods: POST
